<?php
/**
 * Copyright (c) 2018. Komplizierte Technologien. All rights reserved.
 * See COPYING.txt for license details.
 */

namespace KT\RestApiSystem\Model;

use Magento\Framework\Model\AbstractModel;
use KT\RestApiSystem\Api\Data\UrlRewriteInterface;

class UrlRewrite extends AbstractModel implements UrlRewriteInterface
{
    /**
     * Define resource model
     */
    protected function _construct()
    {
        $this->_init('Magento\UrlRewrite\Model\ResourceModel\UrlRewrite');
    }

    /**
     * @inheritdoc
     */
    public function getEntityType()
    {
        return $this->getData(self::ENTITY_TYPE);
    }

    /**
     * @inheritdoc
     */
    public function setEntityType($entityType)
    {
        return $this->setData(self::ENTITY_TYPE, $entityType);
    }

    /**
     * @inheritdoc
     */
    public function getRequestPath()
    {
        return $this->getData(self::REQUEST_PATH);
    }

    /**
     * @inheritdoc
     */
    public function setRequestPath($requestPath)
    {
        return $this->setData(self::REQUEST_PATH, $requestPath);
    }

    /**
     * @inheritdoc
     */
    public function getTargetPath()
    {
        return $this->getData(self::TARGET_PATH);
    }

    /**
     * @inheritdoc
     */
    public function setTargetPath($targetPath)
    {
        return $this->setData(self::TARGET_PATH, $targetPath);    }

    /**
     * @inheritdoc
     */
    public function getRedirectType()
    {
        return $this->getData(self::REDIRECT_TYPE);
    }

    /**
     * @inheritdoc
     */
    public function setRedirectType($redirectType)
    {
        return $this->setData(self::REDIRECT_TYPE, $redirectType);    }

    /**
     * @inheritdoc
     */
    public function getStoreId()
    {
        return $this->getData(self::STORE_ID);
    }

    /**
     * @inheritdoc
     */
    public function setStoreId($storeId)
    {
        return $this->setData(self::STORE_ID, $storeId);
    }

    /**
     * @inheritdoc
     */
    public function getDescription()
    {
        return $this->getData(self::DESCRIPTION);
    }

    /**
     * @inheritdoc
     */
    public function setDescription($description)
    {
        return $this->setData(self::DESCRIPTION, $description);
    }

    /**
     * @inheritdoc
     */
    public function getIsAutogenerated()
    {
        return $this->getData(self::IS_AUTOGENERATED);
    }

    /**
     * @inheritdoc
     */
    public function setIsAutogenerated($isAutogenerated)
    {
        return $this->setData(self::IS_AUTOGENERATED, $isAutogenerated);
    }

    /**
     * @inheritdoc
     */
    public function getMetadata()
    {
        return $this->getData(self::METADATA);
    }

    /**
     * @inheritdoc
     */
    public function setMetadata($metadata)
    {
        return $this->setData(self::METADATA, $metadata);
    }
}